spring:
  profiles.active: local

server.port: 8081
source.file.name: ./apache-access-log.txt

---
spring:
  profiles: local
kafka:
  producer:
    data:
      bootstrapServers: localhost:9092
      ack: 1
      retriesConfig: 3
      batchSize: 1000
      lingerms: 2
      maxInflightConnections: 1
      topic: apache-log-msg
      bufferMemory: 20000
