spring:
  profiles.active: local

server.port: 8081
source.file.name: ./sample-data/usecase2/logs

---
spring:
  profiles: local
kafka:
  producer:
    data:
      bootstrapServers: localhost:9092
      ack: 1
      retriesConfig: 3
      batchSize: 0
      lingerms: 2
      maxInflightConnections: 1
      topic: apache-log-msg
      bufferMemory: 241452
